# Generated by Django 2.0.6 on 2018-07-03 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ('locality', 'route', 'street_number'),
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=165)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='NA', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'ordering': ('state', 'city'),
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('intro', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, default=0)),
                ('latitude', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('last_changed', models.DateTimeField()),
                ('loan_id', models.CharField(default='NA', max_length=50)),
                ('property_type', models.CharField(blank=True, choices=[('1', 'SFR'), ('2', 'CONDO'), ('3', 'COOP'), ('4', '2-4 Units'), ('5', 'Townhouse'), ('6', 'PUD'), ('7', '5+ Units'), ('M', 'Manufactured Hsng'), ('Z', 'Other')], max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('size', models.FloatField(default=0)),
                ('lot_size', models.FloatField(default=0)),
                ('style', models.CharField(blank=True, max_length=30)),
                ('bedroom', models.IntegerField(default=0)),
                ('bath', models.IntegerField(default=0)),
                ('half_bath', models.IntegerField(default=0)),
                ('total_room', models.IntegerField(default=0)),
                ('garage_style', models.CharField(blank=True, max_length=30)),
                ('garage_stall', models.IntegerField(default=0)),
                ('basement', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('list_price', models.FloatField(default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Address')),
                ('favorite_by', models.ManyToManyField(blank=True, related_name='prop_favorite_by', to=settings.AUTH_USER_MODEL)),
                ('pictures', models.ManyToManyField(blank=True, related_name='pics_belongs_to', to='website.Picture')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_list',
            field=models.ManyToManyField(related_name='liked_prop', to='website.Property'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('city', 'postal_code', 'state')},
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='website.Locality'),
        ),
    ]
